<?php

namespace ConferenceSchedulerBundle\Repository;

/**
 * CurriculumLecturerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConferenceLecturerRepository extends \Doctrine\ORM\EntityRepository
{
}
