<?php

namespace ConferenceSchedulerBundle\Repository;

use Doctrine\ORM\EntityRepository;
use ConferenceSchedulerBundle\Entity\Conference;

/**
 * ConferenceUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConferenceUserRepository extends EntityRepository {

    /**
     * Count all users in conference
     * 
     * @param \ConferenceSchedulerBundle\Entity\Conference $conference
     * @return int
     */
    public function countByConference(Conference $conference) {
        $result = $this->createQueryBuilder('t')
                ->select('COUNT(t) total')
                ->where('t.conference = :conference')
                ->setParameter('conference', $conference)
                ->getQuery()
                ->getSingleResult();

        return $result['total'];
    }

}
