<?php

namespace ConferenceSchedulerBundle\Repository;

/**
 * ConferenceAdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConferenceAdminRepository extends \Doctrine\ORM\EntityRepository
{
}
