<?php

namespace ConferenceSchedulerBundle\Repository;

/**
 * CurriculumUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConferenceUserRepository extends \Doctrine\ORM\EntityRepository
{
}
