<?php

namespace ConferenceSchedulerBundle\Repository;

/**
 * ConferenceProgramRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConferenceProgramRepository extends \Doctrine\ORM\EntityRepository
{
}
