<?php

namespace ConferenceSchedulerBundle\Repository;

use Doctrine\ORM\EntityRepository;
use ConferenceSchedulerBundle\Entity\User;
use ConferenceSchedulerBundle\Entity\Venue;

/**
 * HallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HallRepository extends EntityRepository {

    /**
     * Find all conferences for user
     * 
     * @param User $user
     * @return \Doctrine\ORM\Query
     */
    public function findAllByVenueAndAccessQuery(Venue $venue, User $user = null) {
        $result = $this->createQueryBuilder('t')
                ->where('t.venue = :venue')
                ->setParameter('venue', $venue)
                ->orderBy('t.name', 'ASC')
                ->getQuery()
        ;

        return $result;
    }

}
