<?php

namespace ConferenceSchedulerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HallRepository extends EntityRepository
{
//    public function findByVenue() {
//        $this->createQueryBuilder('t')
//                ->innerJoin('t.venue', 'v')
//                ->where('')
//    }
}
